"""Statistical rigor and reproducibility utilities for SmartBio.

These helpers operate on frozen predictions and metadata. They do not fit
predictive models or select features/hyperparameters.
"""
from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json

import numpy as np
import pandas as pd

from .regression import regression_metrics


@dataclass(frozen=True)
class PermutationTestResult:
    metric: str
    observed: float
    null_mean: float
    null_std: float
    p_value: float
    n_permutations: int
    n: int


def _validate(y_true, y_pred) -> tuple[np.ndarray, np.ndarray]:
    y = np.asarray(y_true, dtype=float).reshape(-1)
    p = np.asarray(y_pred, dtype=float).reshape(-1)
    if y.size == 0 or y.shape != p.shape:
        raise ValueError("Inputs must be non-empty arrays with equal length.")
    if not np.isfinite(y).all() or not np.isfinite(p).all():
        raise ValueError("Inputs must contain only finite values.")
    return y, p


def permutation_test(
    y_true,
    y_pred,
    *,
    metric: str = "mae",
    n_permutations: int = 2000,
    random_state: int = 42,
) -> PermutationTestResult:
    """Test whether observed prediction performance exceeds a permutation null.

    For error metrics, smaller is better. The null distribution is generated by
    permuting predictions relative to targets while preserving both marginals.
    The p-value is the fraction of null scores at least as good as observed.
    """
    y, p = _validate(y_true, y_pred)
    if metric not in {"mae", "rmse"}:
        raise ValueError("metric must be 'mae' or 'rmse'.")
    if n_permutations < 100:
        raise ValueError("n_permutations must be at least 100.")
    if random_state < 0:
        raise ValueError("random_state must be non-negative.")

    observed = float(regression_metrics(y, p)[metric])
    rng = np.random.default_rng(random_state)
    null = np.empty(n_permutations, dtype=float)
    for i in range(n_permutations):
        null[i] = regression_metrics(y, rng.permutation(p))[metric]

    p_value = float((1 + np.sum(null <= observed)) / (n_permutations + 1))
    return PermutationTestResult(
        metric=metric,
        observed=observed,
        null_mean=float(np.mean(null)),
        null_std=float(np.std(null, ddof=1)),
        p_value=p_value,
        n_permutations=n_permutations,
        n=int(y.size),
    )


@dataclass(frozen=True)
class ExperimentManifest:
    dataset: str
    dataset_version: str
    split_protocol: str
    feature_set: str
    model: str
    calibration_id: str
    uncertainty_id: str
    random_seed: int
    manifest_hash: str

    @classmethod
    def create(
        cls,
        *,
        dataset: str,
        dataset_version: str,
        split_protocol: str,
        feature_set: str,
        model: str,
        calibration_id: str,
        uncertainty_id: str,
        random_seed: int,
    ) -> "ExperimentManifest":
        fields = {
            "dataset": dataset,
            "dataset_version": dataset_version,
            "split_protocol": split_protocol,
            "feature_set": feature_set,
            "model": model,
            "calibration_id": calibration_id,
            "uncertainty_id": uncertainty_id,
            "random_seed": int(random_seed),
        }
        if any(not str(v).strip() for k, v in fields.items() if k != "random_seed"):
            raise ValueError("manifest identifiers must be non-empty.")
        if random_seed < 0:
            raise ValueError("random_seed must be non-negative.")
        canonical = json.dumps(fields, sort_keys=True, separators=(",", ":"))
        digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        return cls(**fields, manifest_hash=digest)


def leakage_audit(
    frame: pd.DataFrame,
    *,
    patient_col: str = "patient_id",
    device_col: str = "device_model",
    acquisition_col: str = "acquisition_id",
) -> dict[str, int]:
    """Audit duplicate patient/acquisition identities before model evaluation."""
    required = {patient_col, device_col, acquisition_col}
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"missing required columns: {sorted(missing)}")
    if frame.empty:
        raise ValueError("frame must not be empty.")

    patient_dup = int(frame[patient_col].duplicated().sum())
    acquisition_dup = int(frame[acquisition_col].duplicated().sum())
    patient_device_pairs = frame[[patient_col, device_col]].drop_duplicates()
    duplicate_patient_devices = int(
        patient_device_pairs.duplicated(subset=[patient_col]).sum()
    )
    return {
        "n_rows": int(len(frame)),
        "n_unique_patients": int(frame[patient_col].nunique()),
        "duplicate_patient_rows": patient_dup,
        "duplicate_acquisition_rows": acquisition_dup,
        "patients_seen_on_multiple_devices": duplicate_patient_devices,
    }
